services:
  database:
    platform: linux/x86_64
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/database:/var/lib/mysql:rw
      - ./sql:/docker-entrypoint-initdb.d/
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.37.0
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  api:
    image: api:latest
    restart: unless-stopped
    ports:
      - '3001:3001'
      - '9100:9100'
    environment:
      - APP_PORT=3001
      - WEB_URL=*
      - DB_HOST_SOURCE=database
      - DB_HOST_REPLICA=database
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=todo_development
      - DB_PORT=3306
      - METRICS_SERVER_PORT=9100
    depends_on:
      - database
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:9.0.0
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/grafana:/var/lib/grafana"
    networks:
      - monitoring

networks:
  monitoring:
