services:
  mysql:
    platform: linux/x86_64
    image: mysql:9.1.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - ./docker/mysql-volume:/var/lib/mysql:rw
      - ./sql:/docker-entrypoint-initdb.d/
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
